version: '3'

services:
  similar_listings:
    build: similar_listings/
    depends_on:
      - 'database'
    ports: 
      - '3003:3003'
    command: >
      sh -c "npm run seed && npm run react-prod && npm start"
  database:
    image: mongo:latest
