var listings = [
  {
    id: 1,
    images: [],
    saved: 0,
    type: 'ENTIRE HOUSE',
    beds: '2 BEDS',
    title: 'Casa Indian Cove - Desert Tropical Home',
    price: 115,
    ratings: 19,
    average_rating: 5,
  },
  {
    id: 2,
    images: [],
    saved: 0,
    type: 'ENTIRE HOUSE',
    beds: '3 BEDS',
    title: 'Joshua Tree - Indian Cove View Home',
    price: 100,
    ratings: 140,
    average_rating: 5,
  },
  {
    id: 3,
    images: [],
    saved: 0,
    type: 'CAMPER/RV',
    beds: '3 BEDS',
    title: 'Hip Joshua Tree Desert Airstream',
    price: 59,
    ratings: 284,
    average_rating: 5,
  },
  {
    id: 4,
    images: [],
    saved: 0,
    type: 'ENTIRE CABIN',
    beds: '1 BED',
    title: 'Joshua Tree 1954 Homestead Cabin',
    price: 129,
    ratings: 626,
    average_rating: 5,
  },
  {
    id: 5,
    images: [],
    saved: 0,
    type: 'ENTIRE HOUSE',
    beds: '2 BEDS',
    title: 'Joshua Tree Green Haus /w Hot Tub',
    price: 195,
    ratings: 403,
    average_rating: 5,
  },
  {
    id: 6,
    images: [],
    saved: 0,
    type: 'ENTIRE HOUSE',
    beds: '3 BEDS',
    title: 'LOST HOUSE Joshua Tree//Close to Park/Village',
    price: 119,
    ratings: 212,
    average_rating: 5,
  },
  {
    id: 7,
    images: [],
    saved: 0,
    type: 'ENTIRE CABIN',
    beds: '2 BEDS',
    title: 'Mid-Century Hiking & Camping Cabin in Joshua Tree',
    price: 39,
    ratings: 449,
    average_rating: 5,
  },
  {
    id: 8,
    images: [],
    saved: 0,
    type: 'ENTIRE HOUSE',
    beds: '2 BEDS',
    title: 'Moonlite Mesa Cabin, Joshua Tree',
    price: 129,
    ratings: 77,
    average_rating: 5,
  },
  {
    id: 9,
    images: [],
    saved: 0,
    type: 'PRIVATE ROOM IN CAMPER/RV',
    beds: '1 BED',
    title: 'sound of silence 1964 airstream',
    price: 140,
    ratings: 114,
    average_rating: 5,
  },
  {
    id: 10,
    images: [],
    saved: 0,
    type: 'ENTIRE HOUSE',
    beds: '2 BEDS',
    title: 'The Joshua Tree Chalet',
    price: 87,
    ratings: 144,
    average_rating: 5,
  },
  {
    id: 11,
    images: [],
    saved: 0,
    type: 'ENTIRE HOUSE',
    beds: '2 BEDS',
    title: 'Desert Garden House',
    price: 140,
    ratings: 215,
    average_rating: 5,
  },
  {
    id: 12,
    images: [],
    saved: 0,
    type: 'DOME HOUSE',
    beds: '2 BEDS',
    title: 'Dome in the Desert in Joshua Tree',
    price: 160,
    ratings: 516,
    average_rating: 5,
  },
  {
    id: 13,
    images: [],
    saved: 0,
    type: 'ENTIRE HOUSE',
    beds: '3 BEDS',
    title: 'Havalina High Desert Homestead',
    price: 115,
    ratings: 338,
    average_rating: 5,
  }
];